'use strict';

import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import boxen from 'boxen';
import gitUtils from '../utils/git.js';
import messages from '../utils/messages.js';
import detectProjectType from '../utils/detector.js';

async function ignoreCommand() {
    try {
        // Check repo first
        const repo = await gitUtils.checkRepo();
        if (!repo) return;

        const cwd = process.cwd();
        const gitignorePath = path.join(cwd, '.gitignore');

        // Detect project type
        const project = detectProjectType(cwd);

        // Read existing .gitignore
        let existing = '';
        if (fs.existsSync(gitignorePath)) {
            existing = fs.readFileSync(gitignorePath, 'utf8');
        }

        // Find patterns not already in .gitignore
        let toAdd = project.ignoredPatterns.filter(p => !existing.includes(p));

        // Always add general patterns if missing
        const generalPatterns = [
            '.DS_Store',
            'Thumbs.db',
            '*.log',
            '.env',
            '.env.*',
            '*.pem',
            '*.key',
        ];

        generalPatterns.forEach(p => {
            if (!existing.includes(p)) toAdd.push(p);
        });

        // Remove duplicates
        toAdd = [...new Set(toAdd)];

        // Nothing to add
        if (toAdd.length === 0) {
            console.log(
                boxen(
                    chalk.green('✅ Your .gitignore is already perfect!\n\n') +
                    chalk.gray('Nothing new to add.'),
                    {
                        padding: 1,
                        borderColor: 'green',
                        title: '🤖 NexGit Ignore',
                        titleAlignment: 'center'
                    }
                )
            );
            return;
        }

        // Write to .gitignore
        const newContent = existing
            ? existing + '\n# Added by NexGit 🤖\n' + toAdd.join('\n') + '\n'
            : '# Generated by NexGit 🤖\n' + toAdd.join('\n') + '\n';

        fs.writeFileSync(gitignorePath, newContent);

        // Build output
        let output = '';

        if (project.detectedStacks.length > 0) {
            output += chalk.cyan(`🔍 Detected: ${project.detectedStacks.join(', ')}\n\n`);
        } else {
            output += chalk.cyan('🔍 No specific stack detected — adding general patterns\n\n');
        }

        output += chalk.green.bold('✅ Added to .gitignore:\n');
        toAdd.forEach(p => {
            output += chalk.green(`   + ${p}\n`);
        });

        output += chalk.yellow('\n⚠️  These files will now be ignored by Git!\n');
        output += chalk.gray('Run nexgit status to see the difference.');

        console.log(
            boxen(output, {
                padding: 1,
                borderColor: 'green',
                title: '🤖 Nexgit Ignore',
                titleAlignment: 'center'
            })
        );

    } catch (error) {
        messages.gitError(error.message);
    }
}

export default ignoreCommand;