'use strict';

import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import boxen from 'boxen';
import gitUtils from '../utils/git.js';
import messages from '../utils/messages.js';
import detectProjectType from '../utils/detector.js';
import config from '../utils/config.js';

const SERVER_URL = 'https://nexgit-server.onrender.com';

// Fallback hardcoded patterns if server fails
const fallbackPatterns = [
    'node_modules/', 'dist/', 'build/', '.env', '.env.*',
    '*.log', '.DS_Store', 'Thumbs.db', '*.pem', '*.key',
    'bin/', 'obj/', '.vs/', '__pycache__/', 'venv/'
];

// Call AI server for gitignore patterns
async function getAIPatterns(projectType, detectedStacks = []) {
    try {
        const response = await fetch(`${SERVER_URL}/gitignore`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                projectType,
                detectedStacks,
                language: config.getLanguage()
            })
        });

        if (!response.ok) throw new Error('Server error');

        const data = await response.json();
        return data;

    } catch (error) {
        return null;
    }
}

async function ignoreCommand() {
    try {
        // Check repo first
        const repo = await gitUtils.checkRepo();
        if (!repo) return;

        const cwd = process.cwd();
        const gitignorePath = path.join(cwd, '.gitignore');

        // Step 1 — Scan folder with detector
        process.stdout.write(chalk.cyan('🔍 Scanning your project...  '));
        const project = detectProjectType(cwd);
        console.log(chalk.green('✅'));

        // Step 2 — Get AI patterns
        process.stdout.write(chalk.cyan('🤖 Generating patterns...    '));

        let aiResult = null;
        let patterns = [];
        let detectedStack = 'Generic';

        if (project.detectedStacks.length > 0) {
            // Stacks detected — send to AI
            aiResult = await getAIPatterns('detected', project.detectedStacks);
        } else {
            // Nothing detected — generic
            aiResult = await getAIPatterns('generic', []);
        }

        if (aiResult && aiResult.patterns) {
            patterns = aiResult.patterns;
            detectedStack = aiResult.detectedStack || detectedStack;
            console.log(chalk.green('✅'));
        } else {
            // Fallback
            patterns = [...project.ignoredPatterns, ...fallbackPatterns];
            console.log(chalk.yellow('⚠️  (using fallback patterns)'));
        }

        // Step 3 — Read existing .gitignore
        let existing = '';
        if (fs.existsSync(gitignorePath)) {
            existing = fs.readFileSync(gitignorePath, 'utf8');
        }

        // Step 4 — Find what's missing
        const toAdd = [...new Set(patterns)].filter(p => !existing.includes(p));

        // Nothing to add
        if (toAdd.length === 0) {
            console.log(
                boxen(
                    chalk.green('✅ Your .gitignore is already perfect!\n\n') +
                    chalk.gray('Nothing new to add.'),
                    {
                        padding: 1,
                        borderColor: 'green',
                        title: '🤖 NexGit Ignore',
                        titleAlignment: 'center'
                    }
                )
            );
            return;
        }

        // Step 5 — Write to .gitignore
        const newContent = existing
            ? existing + '\n# Updated by NexGit 🤖\n' + toAdd.join('\n') + '\n'
            : '# Generated by NexGit 🤖\n' + toAdd.join('\n') + '\n';

        fs.writeFileSync(gitignorePath, newContent);

        // Step 6 — Show result
        let output = '';

        if (project.detectedStacks.length > 0) {
            output += chalk.cyan(`🔍 Detected: ${project.detectedStacks.join(', ')}\n\n`);
        } else {
            output += chalk.cyan('🔍 No specific stack detected — added general patterns\n\n');
        }

        output += chalk.green.bold(`✅ Added ${toAdd.length} patterns to .gitignore:\n`);
        toAdd.forEach(p => {
            output += chalk.green(`   + ${p}\n`);
        });

        output += chalk.yellow('\n⚠️  These files will now be ignored by Git!\n');
        output += chalk.gray('Run nexgit status to see the difference.');

        console.log(
            boxen(output, {
                padding: 1,
                borderColor: 'green',
                title: '🤖 NexGit Ignore',
                titleAlignment: 'center'
            })
        );

    } catch (error) {
        messages.gitError(error.message);
    }
}

export default ignoreCommand;